# Generated by Django 6.0.3 on 2026-05-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('role', models.CharField(max_length=80)),
                ('department', models.CharField(choices=[('MANAGEMENT', 'Management'), ('SALES', 'Sales'), ('FOREMAN', 'Site Foreman'), ('ADMIN', 'Administration'), ('LABOUR', 'Labour')], default='LABOUR', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='employees/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=160)),
                ('client_name', models.CharField(blank=True, max_length=140)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PLANNING', max_length=20)),
                ('estimated_value', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.FileField(blank=True, upload_to='projects/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('method', models.CharField(choices=[('ECOCASH', 'EcoCash'), ('MASTERCARD', 'Mastercard'), ('VISA', 'Visa')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='company.quoterequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company.project')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
